language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

# -- DISABLED:
#  - "nightly"
#
# NOTE: nightly = 3.8-dev

# -- TEST-BALLON: Check if Python 3.6 is actually Python 3.5.1 or newer
matrix:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install -q -r py.requirements/ci.travis.txt
  - pip show setuptools
  - python setup.py -q install

script:
  - python --version
  - pytest tests
# No behave tests for the time being
#  - behave -f progress --junit features/

after_failure:
# No behave tests for the time being
#  - echo "FAILURE DETAILS (from XML reports):"
#  - bin/behave.junit_filter.py --status=failed reports

# -- ALTERNATIVE:
#  egrep -L 'errors="0"|failures="0"' reports/*.xml | xargs -t cat

# -- USE: New container-based infrastructure for faster startup.
#    http://docs.travis-ci.com/user/workers/container-based-infrastructure/
#
# SEE ALSO:
#   http://lint.travis-ci.org
#   http://docs.travis-ci.com/user/caching/
#   http://docs.travis-ci.com/user/multi-os/  (Linux, MACOSX)
